### ISSUE TITLE
python2.7版本，命令“pip intall lac”一直安装不上。

### ISSUE THREAD

**Issue by DaiJitao** [baidu/lac#116]
pip install lac 一直报错，报错如下  
Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /data/sysdir/servers/anaconda2/bin/python /data/home/ds/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpQgIH1c
       cwd: /tmp/pip-install-ILzYqM/opencv-python
  Complete output (22 lines):
  Traceback (most recent call last):
    File "/data/home/ds/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/data/home/ds/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/data/home/ds/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-SxqOui/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-SxqOui/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-SxqOui/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 243, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-SxqOui/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 448, in <module>
      main()
    File "setup.py", line 99, in main
      % {"ext": re.escape(sysconfig.get_config_var("EXT_SUFFIX"))}
    File "/data/sysdir/servers/anaconda2/lib/python2.7/re.py", line 210, in escape
      s = list(pattern)
  TypeError: 'NoneType' object is not iterable

**Comment by moberq** [comment]
> pip install lac 一直报错，报错如下
> Getting requirements to build wheel ... error
> ERROR: Command errored out with exit status 1:
> command: /data/sysdir/servers/anaconda2/bin/python /data/home/ds/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpQgIH1c
> cwd: /tmp/pip-install-ILzYqM/opencv-python
> Complete output (22 lines):
> Traceback (most recent call last):
> File "/data/home/ds/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in
> main()
> File "/data/home/ds/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
> json_out['return_val'] = hook(**hook_input['kwargs'])
> File "/data/home/ds/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
> return hook(config_settings)
> File "/tmp/pip-build-env-SxqOui/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
> return self._get_build_requires(config_settings, requirements=['wheel'])
> File "/tmp/pip-build-env-SxqOui/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
> self.run_setup()
> File "/tmp/pip-build-env-SxqOui/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 243, in run_setup
> self).run_setup(setup_script=setup_script)
> File "/tmp/pip-build-env-SxqOui/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
> exec(compile(code, **file**, 'exec'), locals())
> File "setup.py", line 448, in
> main()
> File "setup.py", line 99, in main
> % {"ext": re.escape(sysconfig.get_config_var("EXT_SUFFIX"))}
> File "/data/sysdir/servers/anaconda2/lib/python2.7/re.py", line 210, in escape
> s = list(pattern)
> TypeError: 'NoneType' object is not iterable

第4行的command看起来似乎有些奇怪？（anaconda2/bin/python 执行 .local/lib/python2.7/...）
command: /data/sysdir/servers/anaconda2/bin/python /data/home/ds/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py

**Comment by SmilingXinyi** [comment]
**pip2 install opencv-python==4.2.0.32**

> https://stackoverflow.com/questions/63346648/python-2-7-installing-opencv-via-pip-virtual-environment/63355706#63355706
