### ISSUE TITLE
lac分词报cuda错误

### ISSUE THREAD

**Issue by biubiuyi** [baidu/lac#144]
aistudio 中，paddlehub  1.6.0, paddlepaddle 1.7 
```
lac.lexical_analysis(texts=[s], use_gpu=True, batch_size=1,return_tag=False)
```

报错如下，请问是什么原因呢
```
Traceback (most recent call last):
  File "/home/aistudio/.paddlehub/modules/lac/module.py", line 328, in lexical_analysis
    _places = os.environ["CUDA_VISIBLE_DEVICES"]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'CUDA_VISIBLE_DEVICES'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 74, in <module>
    train_loss, train_f1 = run_exe(data_g=train_generator, gram=train_program, fetch_l=[train_loss]+fetches,if_f1=cfg['train_params']['if_f1'])
  File "main.py", line 61, in run_exe
    for d in data_g:
  File "/home/aistudio/wordembeddingV2/datasets.py", line 116, in __iter__
    text_words = self.tokenize(text) #分词
  File "/home/aistudio/wordembeddingV2/datasets.py", line 84, in tokenize
    return self.lac.lexical_analysis(texts=[s], use_gpu=cfg['train_params']['use_cuda'], batch_size=1,return_tag=False)[0]['word']
  File "/home/aistudio/.paddlehub/modules/lac/module.py", line 332, in lexical_analysis
    "Environment Variable CUDA_VISIBLE_DEVICES is not set correctly. If you wanna use gpu, please set CUDA_VISIBLE_DEVICES as cuda_device_id."
RuntimeError: Environment Variable CUDA_VISIBLE_DEVICES is not set correctly. If you wanna use gpu, please set CUDA_VISIBLE_DEVICES as cuda_device_id.
aistudio@jupyter-76239-1173129:~/wordembeddingV2$ 
```

**Comment by biubiuyi** [comment]
参考https://github.com/PaddlePaddle/PaddleHub/issues/993
