### ISSUE TITLE
下载时遇到 gbk 编码错误

### ISSUE THREAD

**Issue by fengwuyun** [baidu/lac#167]
I have encounted a codec problem when I download the LAC-2.1.0

> ERROR: Command errored out with exit status 1:
>      command: 'c:\users\14295\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\14295\\AppData\\Local\\Temp\\pip-install-mvyjg5pm\\lac_62990e8398824b9798fb89c1c5315704\\setup.py'"'"'; __file__='"'"'C:\\Users\\14295\\AppData\\Local\\Temp\\pip-install-mvyjg5pm\\lac_62990e8398824b9798fb89c1c5315704\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\14295\AppData\Local\Temp\pip-pip-egg-info-kg5qp2ya'
>          cwd: C:\Users\14295\AppData\Local\Temp\pip-install-mvyjg5pm\lac_62990e8398824b9798fb89c1c5315704\
>     Complete output (5 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\14295\AppData\Local\Temp\pip-install-mvyjg5pm\lac_62990e8398824b9798fb89c1c5315704\setup.py", line 50, in <module>
>         long_description = fh.read()
>     UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 66: illegal multibyte sequence
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Siuuuu7** [comment]
PR [https://github.com/baidu/lac/pull/166](url) solved this problem
