### ISSUE TITLE
请问一下，LAC是线程安全的么？

### ISSUE THREAD

**Issue by DachuanZhao** [baidu/lac#170]
环境：
python3.6 + lac 2.1.1
报错：
```
Traceback (most recent call last):
  File "/admin/servers/anaconda3/envs/auto_moment/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/admin/servers/anaconda3/envs/auto_moment/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/admin/servers/anaconda3/envs/auto_moment/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/admin/servers/anaconda3/envs/auto_moment/lib/python3.6/concurrent/futures/thread.py", line 69, in _worker
    work_item.run()
  File "/admin/servers/anaconda3/envs/auto_moment/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/admin/servers/anaconda3/envs/auto_moment/lib/python3.6/site-packages/grpc/_server.py", line 552, in _unary_response_in_pool
    argument, request_deserializer)
  File "/admin/servers/anaconda3/envs/auto_moment/lib/python3.6/site-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
> File "/admin/codes/ai_component/handler/ner_stock_model_service.py", line 92, in ner_content
    ) = self.base_ner_model.ner_stock(content)
  File "/admin/codes/ai_component/business/base_ner_model.py", line 98, in ner_stock
    content_tokenize_list, content_category_list = self.lac_obj.run(content)
  File "/admin/servers/anaconda3/envs/auto_moment/lib/python3.6/site-packages/LAC/lac.py", line 81, in run
    return self.model.run(texts)
  File "/admin/servers/anaconda3/envs/auto_moment/lib/python3.6/site-packages/LAC/models.py", line 239, in run
    crf_result = super(LacModel, self).run(texts)['crf_result']
  File "/admin/servers/anaconda3/envs/auto_moment/lib/python3.6/site-packages/LAC/models.py", line 96, in run
    tensor_words, words_length = self.texts2tensor(texts)
  File "/admin/servers/anaconda3/envs/auto_moment/lib/python3.6/site-packages/LAC/models.py", line 129, in texts2tensor
    text = self.segment_tool.fast_cut(text)
  File "/admin/servers/anaconda3/envs/auto_moment/lib/python3.6/site-packages/LAC/segment.py", line 97, in fast_cut
    self.logtotal + route[_+1][0], _) for _ in self.dag[idx])
KeyError: 1442
```

**Comment by Nickname1230** [comment]
需要对每一个线程创建一个LAC对象

**Comment by DachuanZhao** [comment]
> 需要对每一个线程创建一个LAC对象

额。。。那所有lac对象能够共享一个停用词库和自定义词库嘛？还是每次都需要加载一下？如果每次都需要加载一下的话，能提个feature：“实现LAC线程安全” 嘛？
因为多线程在提供接口的时候还是很常见的，多个线程需要共享一个LAC对象。。。
或者单例模式可以解决问题嘛？比如这样：
```Python
class Singleton(type):
    """单例类"""

    _instances = {}

    def __call__(cls, *args, **kwargs):
        if cls not in cls._instances:
            cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
        return cls._instances[cls]

class BaseTokenizeModel(metaclass=Singleton):

    def __init__(self):
        self.lac_obj = LAC.LAC(mode="seg")
```
