### ISSUE TITLE
lac 默认使用最新paddle 会有兼容性问题，建议固定版本范围

### ISSUE THREAD

**Issue by liangpinglk** [baidu/lac#275]
- 2023年12月28 安装了LAC，由于paddle也更新了，LAC 默认依赖安装最新paddle，就导致出现了下面的问题

```shell
root@02ad31ec7a86:/usr/src/app# pip freeze | grep LAC
LAC==2.1.2
root@02ad31ec7a86:/usr/src/app# pip freeze | grep paddle
paddlepaddle==2.6.0
root@02ad31ec7a86:/usr/src/app# python3.8
Python 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import LAC
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/LAC/__init__.py", line 23, in <module>
    from .lac import LAC
  File "/usr/local/lib/python3.8/dist-packages/LAC/lac.py", line 28, in <module>
    import paddle.fluid as fluid
ModuleNotFoundError: No module named 'paddle.fluid'
>>> 

```
- 2023年12月25号安装LAC，此时自动安装的paddle 是2.5.2，是正常的
```
root@822ac3eecbc8:/usr/src/app# pip freeze | grep paddle
paddlepaddle==2.5.2
root@822ac3eecbc8:/usr/src/app# pip freeze | grep LAC
LAC==2.1.2
root@822ac3eecbc8:/usr/src/app# python3.8
Python 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import LAC
>>> 

```

**Comment by liangpinglk** [comment]
起初报的是这种错误，后来命令行调了下才看到真正的错误。。没有把准确的错误信息暴露出来
![image](https://github.com/baidu/lac/assets/25102090/3f4a30a7-8000-40b3-bb7a-999998ba3a92)

**Comment by liangpinglk** [comment]
看了下源码，应该是没有固定版本号范围的，默认最新
<img width="915" alt="image" src="https://github.com/baidu/lac/assets/25102090/95581211-d135-4814-8af0-66e041687ab4">

**Comment by zhang19523zhao** [comment]
怎么解决的大佬

**Comment by liangpinglk** [comment]
@zhang19523zhao lac 分词的包，你找几个版本自己试下，没问题后，把requirements里的版本都固定了
目前我用的paddle和lac的版本是：
```
paddlepaddle==2.5.2
LAC==2.1.2
```

**Comment by XavierSpycy** [comment]
@zhang19523zhao 

```bash
$ pip uninstall paddlepaddle
$ pip install paddlepaddle==2.5.2
```

**Comment by zhang19523zhao** [comment]
pip3  install paddlepaddle==2.5.2 
ERROR: Could not find a version that satisfies the requirement paddlepaddle==2.5.2 (from versions: 2.6.0)
ERROR: No matching distribution found for paddlepaddle==2.5.2
我这显示这个报错

**Comment by zhaolinlee** [comment]
> [@zhang19523zhao](https://github.com/zhang19523zhao)lac分词的包，你找几个版本自己试下，没问题后，把requirements里的版本都固定了， 目前我用的paddle和lac的版本是：
> 
> ```
> paddlepaddle==2.5.2
> LAC==2.1.2
> ```

谢谢大佬，真的这样解决了~~~感谢
