### ISSUE TITLE
ModuleNotFoundError: No module named 'paddle.fluid'

### ISSUE THREAD

**Issue by Gloridust** [baidu/lac#278]
我遇到了如下问题：
```
Traceback (most recent call last):
  File "c:\Users\gloridust\Documents\GitHub\Job-submission-status-Check-tool\main.py", line 10, in <module>
    from LAC import LAC
  File "C:\Users\gloridust\AppData\Local\Programs\Python\Python312\Lib\site-packages\LAC\__init__.py", line 23, in <module>       
    from .lac import LAC
  File "C:\Users\gloridust\AppData\Local\Programs\Python\Python312\Lib\site-packages\LAC\lac.py", line 33, in <module>
    from . import nets
  File "C:\Users\gloridust\AppData\Local\Programs\Python\Python312\Lib\site-packages\LAC\nets.py", line 30, in <module>
    from . import utils
  File "C:\Users\gloridust\AppData\Local\Programs\Python\Python312\Lib\site-packages\LAC\utils.py", line 27, in <module>
    import paddle.fluid as fluid
ModuleNotFoundError: No module named 'paddle.fluid'
···

其中，paddlepaddle和lac都在最新版。

**Comment by Gloridust** [comment]
我从一个issues中了解到`.fluid`在最新版本中已弃用，所以我尝试将LAC包中所有的`.fluid`替换为了`.base`，暂时解决了这个问题。但是我认为这一定不是最好的方法

**Comment by Tominochick** [comment]
> 我从一个issues中了解到`.fluid`在最新版本中已弃用，所以我尝试将LAC包中所有的`.fluid`替换为了`.base`，暂时解决了这个问题。但是我认为这一定不是最好的方法

降低paddle的版本，如果这个项目只用这一个库的话。这个库上一次pr在2021。
```bash
pip install paddlepaddle==2.4.1 
```
2.5以下到可以。

**Comment by hulaoop** [comment]
把.fluid改成.base增量训练有报错：module 'paddle.base.layers' has no attribute 'data'

**Comment by jiaohuix** [comment]
> > 我从一个issues中了解到`.fluid`在最新版本中已弃用，所以我尝试将LAC包中所有的`.fluid`替换为了`.base`，暂时解决了这个问题。但是我认为这一定不是最好的方法
> 
> 降低paddle的版本，如果这个项目只用这一个库的话。这个库上一次pr在2021。
> 
> ```shell
> pip install paddlepaddle==2.4.1 
> ```
> 
> 2.5以下到可以。

@Tominochick  谢谢大佬，已解决

**Comment by piscesvivian** [comment]
我也遇到这个问题了。 @Tominochick 
不仅需要安装paddlepaddle==2.4.1 ，还要降级Python 到 3.10

[https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4/install/index_cn.html](url)

**Comment by wuhua111** [comment]
python3.12 用2.51版的没问题
