### ISSUE TITLE
运行train.py 报错

### ISSUE THREAD

**Issue by tiandilinghuo** [baidu/lac#37]
Traceback (most recent call last):
  File "train.py", line 338, in <module>
    train(args)
  File "train.py", line 295, in train
    fluid.io.save_inference_model(temp_save_model, ['word', 'target'], [num_infer_chunks, num_label_chunks, num_correct_chunks], save_exe)
  File "/usr/local/python3.6.6/lib/python3.6/site-packages/paddle/fluid/io.py", line 954, in save_inference_model
    var, 1., name="save_infer_model/scale_{}".format(i))
  File "/usr/local/python3.6.6/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 8848, in scale
    name=name, dtype=x.dtype, persistable=False)
  File "/usr/local/python3.6.6/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 366, in create_variable
    return self.main_program.current_block().create_var(*args, **kwargs)
  File "/usr/local/python3.6.6/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1198, in create_var
    var = Variable(block=self, *args, **kwargs)
  File "/usr/local/python3.6.6/lib/python3.6/site-packages/paddle/fluid/framework.py", line 350, in __init__
    dtype))
ValueError: Variable save_infer_model/scale_0 has been created before. The previous data type is VarType.FP32; the new data type is VarType.INT64. They are not matched.

**Comment by hpsdy** [comment]
遇到了同样的问题

**Comment by hpsdy** [comment]
项目没有人维护了么？

**Comment by jshower** [comment]
是在什么paddle版本下遇到的问题呢？paddle版本前后有些不兼容，如果使用较新版的paddle可能会遇到代码跑不通的情况。建议在v1.1分支下，使用paddlev1.1版本。在master分支下，使用paddle 0.14.0版本。

**Comment by qindisky** [comment]
使用了hub.baidubce.com/paddlepaddle/paddle:1.1.0的镜像，按照步骤操作的，报错信息如下
Traceback (most recent call last):
  File "python/train.py", line 325, in <module>
    train(args)
  File "python/train.py", line 206, in train
    word_dict_len = max(map(int, word2id_dict.values())) + 1
ValueError: max() arg is an empty sequence
是需要配置conf下的字典么，如何配置，请指点下
