### ISSUE TITLE
UnicodeEncodeError on Chinese

### ISSUE THREAD

**Issue by lishoujun** [baidu/lac#60]
Hi，my Python version is  Python 2.7.17 |Anaconda custom (64-bit)| (default, Oct 21 2019, 19:04:46)
After pip install lac, I exec lac and input Chinese to test,then have an UnicodeEncodeError
```
$ lac
百度开源词法分析工具LAC2.0
Traceback (most recent call last):
  File "/home/lishoujun/anaconda2/bin/lac", line 8, in <module>
    sys.exit(main())
  File "/home/lishoujun/anaconda2/lib/python2.7/site-packages/LAC/cmdline.py", line 60, in main
    for word, tag in zip(words, tags)))
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256)
```

**Comment by Bond-H** [comment]
Maybe you should exec `export PYTHONIOENCODING=UTF-8` to set the sys.stdout.encoding
