### ISSUE TITLE
同时分多个句子时不稳定

### ISSUE THREAD

**Issue by DachuanZhao** [baidu/lac#99]
```
Traceback (most recent call last):
  File "temp.py", line 27, in <module>
    res_list.append(lac.run(line_list[i*chunk_size : (i+1)*chunk_size]))
  File "/home/zhaodachuan/anaconda3/lib/python3.7/site-packages/LAC/lac.py", line 105, in run
    crf_decode = self.predictor.run([tensor_words])
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::PaddleTensorToLoDTensor(paddle::PaddleTensor const&, paddle::framework::LoDTensor*, paddle::platform::Place const&)
3   paddle::AnalysisPredictor::SetFeed(std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> > const&, paddle::framework::Scope*)
4   paddle::AnalysisPredictor::Run(std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> > const&, std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> >*, int)


----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The data contained in the input PaddleTensor is illegal.
  [Hint: pt.data.data() should not be null.] at (/paddle/paddle/fluid/inference/api/analysis_predictor.cc:99)

terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::PaddleBuf::Free()
2   paddle::PaddleTensor::~PaddleTensor()

----------------------
Error Message Summary:
----------------------
Error: An error occurred here. There is no accurate error hint for this error yet. We are continuously in the process of increasing hint for this kind of error check. It would be helpful if you could inform us of how this conversion went by opening a github issue. And we will resolve it with high priority.
  - New issue link: https://github.com/PaddlePaddle/Paddle/issues/new
  - Recommended issue content: all error stack information
  [Hint: Expected length_ > 0UL, but received length_:0 <= 0UL:0.] at (/paddle/paddle/fluid/inference/api/api.cc:107)

Aborted
```

**Comment by Bond-H** [comment]
从提示上看，应该是因为这多个句子均是空串导致的，所以导致模型输入异常，已复现该问题，感谢反馈。如果基于当前版本使用，可增加条件检查，判断所有句子总长度是否等于0。

**Comment by DachuanZhao** [comment]
> 从提示上看，应该是因为这多个句子均是空串导致的，所以导致模型输入异常，已复现该问题，感谢反馈。如果基于当前版本使用，可增加条件检查，判断所有句子总长度是否等于0。

感谢，回复很及时，点赞~！

**Comment by DachuanZhao** [comment]
> 从提示上看，应该是因为这多个句子均是空串导致的，所以导致模型输入异常，已复现该问题，感谢反馈。如果基于当前版本使用，可增加条件检查，判断所有句子总长度是否等于0。

目前还有一个很奇怪的bug，不知道和这个是否有关系
```
import LAC

lac = LAC.LAC(mode="seg")

print(lac.run(["","dasfdsa"]))
print(lac.run(["","dasfdsa","dasfdsa"]))
```
以上代码在第二个print处会报错。
系统：CentOS7
python版本：python37
LAC版本：2.0.4

**Comment by DachuanZhao** [comment]
> 从提示上看，应该是因为这多个句子均是空串导致的，所以导致模型输入异常，已复现该问题，感谢反馈。如果基于当前版本使用，可增加条件检查，判断所有句子总长度是否等于0。

请问这个bug什么时候会修复呢？2.0.5版本？

**Comment by DachuanZhao** [comment]
> 从提示上看，应该是因为这多个句子均是空串导致的，所以导致模型输入异常，已复现该问题，感谢反馈。如果基于当前版本使用，可增加条件检查，判断所有句子总长度是否等于0。

请问2.0.5版本修复了么？

**Comment by DachuanZhao** [comment]
> 从提示上看，应该是因为这多个句子均是空串导致的，所以导致模型输入异常，已复现该问题，感谢反馈。如果基于当前版本使用，可增加条件检查，判断所有句子总长度是否等于0。

我试了一下，目前还是没有修复，测试代码如下：
```Python
import LAC
lac = LAC.LAC(mode="seg")
lac.run(["","",""])
```

**Comment by DachuanZhao** [comment]
> 从提示上看，应该是因为这多个句子均是空串导致的，所以导致模型输入异常，已复现该问题，感谢反馈。如果基于当前版本使用，可增加条件检查，判断所有句子总长度是否等于0。

2.1.0 版本测试正常了，感谢~
